### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getId()

### ISSUE THREAD

**Issue by bharatvimirlab** [mageplaza/magento-2-customer-approval#10]
While editing existing customer from backend showing following error.

_Fatal error: Uncaught Error: Call to a member function getId() on string in /.../vendor/mageplaza/module-customer-approval/Helper/Data.php_

http://prntscr.com/qwnic9

**Comment by bdtrung** [comment]
Please try to install our Core module, download [link](https://github.com/mageplaza/module-core).

**Comment by bdtrung** [comment]
Close due to no response within 7 days.
