### ISSUE TITLE
404 Error After Registering

### ISSUE THREAD

**Issue by leek** [mageplaza/magento-2-customer-approval#13]
When using this plugin, after registering for a new account, customers are sent to:

```/customer/account/createpost/```

This throws a 404 page, but still shows the `Your account requires approval before you can log in.` flash message (see screenshot).

How can I avoid this 404 and perhaps send them to a "Your account is pending approval" page?

<img width="746" alt="Screen Shot 2020-04-17 at 10 34 59 AM" src="https://user-images.githubusercontent.com/60204/79580530-21943700-8097-11ea-9dd9-370c7d9f0808.png">

**Comment by leek** [comment]
Nevermind - this was an error related to `bitexpert/magento2-force-customer-login` plugin.

**Comment by Arthas7895** [comment]
Great! Glad to hear you've found the problem. If you have other issues with the module, you can go to the issue here and we will discuss it together.
Have a nice day!

**Comment by nenriquez** [comment]
@leek how did you solve it?
