### ISSUE TITLE
Not able to save customer approval from dopdown

### ISSUE THREAD

**Issue by nayanchamp** [mageplaza/magento-2-customer-approval#14]
I am not able to change customer status from the customer dropdown field.

**Comment by Arthas7895** [comment]
You cannot change the status of a customer by using a dropdown field. That's just the status of the customer. You can only change it with the options here (https://prnt.sc/sh8dup).
In the next version, we will disable that dropdown field to avoid misunderstandings (https://prnt.sc/sh8et3)

**Comment by Arthas7895** [comment]
It's been 7 days since I haven't received a response from you, so I'll close this issue here
