### ISSUE TITLE
Feature request: approve accounts of a list of specific company email domains automatically

### ISSUE THREAD

**Issue by amenk** [mageplaza/magento-2-customer-approval#20]
Use case: Specific mail addresses should be automatically be approved. Does that work already or can it be added to that module? Or would it be out of scope?

The idea is to define a list of email-domains, for example

@bigcompany-example.com
@somecompany-example.com

If the user registers with such an email adress, they are approved automatically, for another address, manually.

**Comment by HuyPhuc98** [comment]
Hi,

An automatic customer approval feature is available in the module.
It is in the configuration section of the module Customer Approval || https://prnt.sc/u5x8vk

Thank you!

**Comment by amenk** [comment]
Thanks, Sure but that is not rule based

**Comment by HuyPhuc98** [comment]
I still do not understand what you mean.
Can you describe your request more clearly for me?

Thank you!

**Comment by amenk** [comment]
sorry, I updated the initial comment to make it more clear :)

**Comment by HuyPhuc98** [comment]
Your requirement is beyond the functionality of the Customer Approval module and it is also not feasible to be customized.
Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due to no response within 7 days.
