### ISSUE TITLE
Notification Email Issue

### ISSUE THREAD

**Issue by vivekmands** [mageplaza/magento-2-customer-approval#22]
### Preconditions (*)

1. 2.3.5-p1
2. When new customer registers not getting email notification

### Steps to reproduce (*)

1. Install the Mageplaza CustomerApproval extension and use the customer portal to register as a new customer
2. Message will show but no email 

### Expected result (*)

1. When a new user registers extension should send email notification to admin as well as customer
2.

### Actual result (*)

1. No email notification 
2.

**Comment by xnbs** [comment]
Hi @vivekmands 

I tested it on my local website and everything still works fine.
So I think your problem doesn't stem from our extension. It could be due to email functionality.
Does your website have the smtp extension installed?

**Comment by vivekmands** [comment]
Hi'
Yes, SMTP is installed . in extension we have Auto approve feature if it is
on then admin getting the mail of logged-in but if it is off then no mail
notification comes.

Thanks & Regards,
*Vivek Singh*

M&S Consulting

vivek.singh@mandsconsulting.com

(704) 250-0772

www.mandsconsulting.com

**Comment by sonnb-98** [comment]
Hi @vivekmands 

Can you check if email is in spam mailbox or not?
Let me know which version of this extension you are using?

**Comment by vivekmands** [comment]
Hi ,

Mails are not going in SPAM
Version of extension used: 1.0.4

Thanks & Regards,
*Vivek Singh*

M&S Consulting

vivek.singh@mandsconsulting.com

(704) 250-0772

www.mandsconsulting.com

**Comment by sonnb-98** [comment]
Hi @vivekmands 

Since when Auto-Approval is on, email is only sent to the client and not the administrator, so I guess the module is having a problem.
Please help me try to reinstall module and check if the above problem still occurs.

**Comment by vivekmands** [comment]
Ok will let you know

**Comment by sonnb-98** [comment]
Hi @vivekmands 

I will wait for good news from you.

**Comment by vivekmands** [comment]
hi 

What extension version I should install.
can you share the path(link)  for that

**Comment by vivekmands** [comment]
should i reinstall same 1.0.4

**Comment by sonnb-98** [comment]
Hi @vivekmands 
Yes. Please install the latest version.

**Comment by vivekmands** [comment]
means 1.0.4?

**Comment by sonnb-98** [comment]
Hi @vivekmands 

It's correct. 1.0.4 is our latest version.

**Comment by vivekmands** [comment]
ok

**Comment by vivekmands** [comment]
Reinstalled, checking now

**Comment by sonnb-98** [comment]
Hi @vivekmands 

Please check back and let me know the results.

**Comment by vivekmands** [comment]
same not getting emails notification

**Comment by sonnb-98** [comment]
Hi @vivekmands 

Can you show me the configuration image of the module?

**Comment by vivekmands** [comment]
ok just a minute

**Comment by vivekmands** [comment]
![image](https://user-images.githubusercontent.com/68639548/94791486-56057080-03f5-11eb-8b63-06fa438727bd.png)

**Comment by vivekmands** [comment]
general configuration

**Comment by vivekmands** [comment]
![image](https://user-images.githubusercontent.com/68639548/94791606-851be200-03f5-11eb-8a19-2d89d4d59fcc.png)

**Comment by vivekmands** [comment]
![image](https://user-images.githubusercontent.com/68639548/94791692-a54ba100-03f5-11eb-90e7-1a5dd9b0a6dd.png)

**Comment by vivekmands** [comment]
these three images of extension configuration

**Comment by vivekmands** [comment]
mail sending settings:
![image](https://user-images.githubusercontent.com/68639548/94792647-e3959000-03f6-11eb-8f5c-1a26e6afd7b0.png)

**Comment by vivekmands** [comment]
r u there?

**Comment by sonnb-98** [comment]
Hi @vivekmands 

Yes, I'm still here. I need to check again so please wait a moment.

**Comment by sonnb-98** [comment]
Hi @vivekmands 

Is your condition the same as before the reinstallation?
(This means emails are only sent when you have 'Auto approve' turned on)

**Comment by vivekmands** [comment]
yes

**Comment by sonnb-98** [comment]
Hi @vivekmands 

For the best support on your issue, please create a ticket at the following link: https://mageplaza.freshdesk.com/support/tickets/new

**Comment by vivekmands** [comment]
ok

**Comment by sonnb-98** [comment]
Hi,

Since there is no other problem, I will end the problem now.
