### ISSUE TITLE
Compatibility with Social Login module 

### ISSUE THREAD

**Issue by mkiddo87** [mageplaza/magento-2-customer-approval#25]
### Preconditions (*)

1. Magento: 2.3
2. PHP: 7
3. MySQL: mysql Ver 15.1 Distrib 10.3.22-MariaDB, for Linux (x86_64)

### Steps to reproduce (*)

1. Install mageplaza  Social login and setup any Social platform
2. Enable customer approval module and turn auto approval off
3. Register a new user using email and check that you can't log in without approval
4. User any social platform to Social login in the login page and you will bypass the approval check

### Expected result (*)

1. We should see an error message that the User is pending approval

### Actual result (*)

1.  Social login bypasses the approval completely

**Comment by HuyPhuc98** [comment]
Hi,

Currently, the Customer Approval module is not compatible with the Social Login module.
We will examine the issue and will notify you if it is feasible.

Thank you!

**Comment by mkiddo87** [comment]
is there a quick workaround to make every new customer marked as pending?

**Comment by HuyPhuc98** [comment]
Hi,

I am still in the process of testing the feasibility of whether the Custom Approval module is compatible with the Social Login module.
I will notify you when the test is complete.

Thank you!

**Comment by KhietNguyen83** [comment]
Hi @mkiddo87 ,
We have released compa version with socialLogin.
Please update both modules.
Thank you very much!
