### ISSUE TITLE
Compatibility with customer email confirmation feature

### ISSUE THREAD

**Issue by simonrl** [mageplaza/magento-2-customer-approval#26]
### Description (*)
Magento has a configuration setting that customers need to confirm their email address before they can log in.
We normally enable this setting, and I think it's even legally required for EU countries due to GDPR.

Are there plans on making this module compatible with this setting?

### Expected behavior (*)
I think the following would make sense if "customer requires email confirmation" (`customer/create_account/confirm`) is enabled, and customers also need to be approved by the store owner:
- customer registers
- customer receives Magento's double-opt-in email
- after confirmation, customer receives Mageplaza's "status pending" email and administrator receives "a new account is waiting for approval" email

### Benefits
The new feature would further extend the module's compatibility with Magento core features, and also make it suitable for online shops that try to comply with GDPR. While the current status of the module already has a good feature set, I think Enterprise-level stores rely on the implementation of this feature.

### Additional information
--

**Comment by phamcuongmp** [comment]
Thanks for your useful information. For the time being, Customer Approval and Customer Email Confirmation work separately. We will put this idea on our roadmap and consider making Customer approval compatible with Customer Email Confirmation in the next versions of Customer Approval.
