### ISSUE TITLE
Redirecting to My Account Page Before Approval with Multistore Setup

### ISSUE THREAD

**Issue by xeontcs** [mageplaza/magento-2-customer-approval#27]
### Preconditions (*)

1. Magento 2.3.5-p1

### Steps to reproduce (*)

1. Extension is Disable Globally
2. Account Sharing is Per Website
3. Extension is Enable in One Store View
4. Create an Account in Website 1, Create an Account in Website 2(Enabled) - Both the same Email Address
5. Once you Create an Account in Website 2, You will be automatically redirect to My Account Page

### Expected result (*)

1. Extension to work as expected which "Website 2" account to Pending until Approval.

### Actual result (*)

1. Once you Create an Account in Website 2, You will be automatically redirect to My Account Page. Regardless the extension is enabled and Auto Approve setting is set to No

**Comment by phamcuongmp** [comment]
The problem has been resolved in the ticket: [#28](https://github.com/mageplaza/magento-2-customer-approval/issues/28)
