### ISSUE TITLE
Customer does not exit

### ISSUE THREAD

**Issue by jorgb90** [mageplaza/magento-2-customer-approval#3]
Just installed this extension, but receiving the following exception in the front and backend when trying to login at the frontend or edit a customer in the backend, also mass approving on the customer grid results in a "customer does not exist".

`{"0":"Customer does not exist.","1":"<pre>#1 Mageplaza\\CustomerApproval\\Helper\\Data->getIsApproved() called at [vendor\/mageplaza\/module-customer-approval\/Helper\/Data.php:574]\n#2 Mageplaza\\CustomerApproval\\Helper\\Data->shouldEnableButton() called at [vendor\/mageplaza\/module-customer-approval\/Block\/Adminhtml\/Edit\/NotApprove.php:78]\n#3 Mageplaza\\CustomerApproval\\Block\\Adminhtml\\Edit\\NotApprove->getButtonData() called at [vendor\/magento\/framework\/View\/Element\/UiComponent\/Context.php:285]\n#4 Magento\\Framework\\View\\Element\\UiComponent\\Context->addButtons() called at [vendor\/magento\/module-ui\/Component\/AbstractComponent.php:116]\n#5 Magento\\Ui\\Component\\AbstractComponent->prepare() called at [vendor\/magento\/framework\/View\/Layout\/Generator\/UiComponent.php:164]\n#6 Magento\\Framework\\View\\Layout\\Generator\\UiComponent->prepareComponent() called at [vendor\/magento\/framework\/View\/Layout\/Generator\/UiComponent.php:142]\n#7 Magento\\Framework\\View\\Layout\\Generator\\UiComponent->generateComponent() called at [vendor\/magento\/framework\/View\/Layout\/Generator\/UiComponent.php:103]\n#8 Magento\\Framework\\View\\Layout\\Generator\\UiComponent->process() called at [vendor\/magento\/framework\/View\/Layout\/GeneratorPool.php:81]\n#9 Magento\\Framework\\View\\Layout\\GeneratorPool->process() called at [vendor\/magento\/framework\/View\/Layout.php:343]\n#10 Magento\\Framework\\View\\Layout->generateElements() called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:89]\n#11 Magento\\Framework\\View\\Layout\\Interceptor->generateElements() called at [vendor\/magento\/framework\/View\/Layout\/Builder.php:129]\n#12 Magento\\Framework\\View\\Layout\\Builder->generateLayoutBlocks() called at [vendor\/magento\/framework\/View\/Page\/Builder.php:55]\n#13 Magento\\Framework\\View\\Page\\Builder->generateLayoutBlocks() called at [vendor\/magento\/framework\/View\/Layout\/Builder.php:65]\n#14 Magento\\Framework\\View\\Layout\\Builder->build() called at [vendor\/magento\/framework\/View\/Layout.php:253]\n#15 Magento\\Framework\\View\\Layout->build() called at [vendor\/magento\/framework\/View\/Layout.php:875]\n#16 Magento\\Framework\\View\\Layout->getBlock() called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:414]\n#17 Magento\\Framework\\View\\Layout\\Interceptor->getBlock() called at [vendor\/magento\/module-backend\/Model\/View\/Result\/Page.php:26]\n#18 Magento\\Backend\\Model\\View\\Result\\Page->setActiveMenu() called at [vendor\/magento\/module-customer\/Controller\/Adminhtml\/Index\/Edit.php:56]\n#19 Magento\\Customer\\Controller\\Adminhtml\\Index\\Edit->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#20 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:231]\n#21 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#22 Magento\\Customer\\Controller\\Adminhtml\\Index\\Edit\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#23 Magento\\Customer\\Controller\\Adminhtml\\Index\\Edit\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:143]\n#24 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#25 Magento\\Customer\\Controller\\Adminhtml\\Index\\Edit\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [app\/code\/Bss\/ForceLogin\/Plugin\/OtherPage.php:86]\n#26 Bss\\ForceLogin\\Plugin\\OtherPage->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#27 Magento\\Customer\\Controller\\Adminhtml\\Index\\Edit\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#28 Magento\\Customer\\Controller\\Adminhtml\\Index\\Edit\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Customer\/Controller\/Adminhtml\/Index\/Edit\/Interceptor.php:26]\n#29 Magento\\Customer\\Controller\\Adminhtml\\Index\\Edit\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:159]\n#30 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:99]\n#31 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#32 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#33 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#34 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#35 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:137]\n#36 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n#37 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#38 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:40]\n<\/pre>","url":"\/beheer\/customer\/index\/edit\/id\/121\/key\/d609791590043e0a0852536e577cb6fddb4464fb935846c97bfb10d3985fe8e3\/","script_name":"\/index.php"}`

**Comment by fj-sfd** [comment]
![customer account createpost ](https://user-images.githubusercontent.com/58604743/72285998-400b1200-3612-11ea-9aca-3e3bfddc2ae5.png)

=> same issue on MultiStore website while creating a new customer from Frontend.
=> Also it is not working while trying to edit a customer in the backend, mass approving on the customer grid. 
=> Magento 2.3.3
=> PHP 7.2.26

**Comment by doublesharp** [comment]
I was able to work around this using a plugin to override the Data->approvalAction method. It mostly changes two if statements:
 - `if (is_int($customerOrId) || is_string($customerOrId))`
- `if (!$attribute || $attribute->getValue() != $typeApproval) {`

**etc/di.xml**
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../lib/internal/Magento/Framework/ObjectManager/etc/config.xsd">
    <type name="Mageplaza\CustomerApproval\Helper\Data">
        <plugin 
            name="customerapproval_helper" 
            type="Vendor\Module\Plugin\CustomerApproval\Helper\Data" 
            sortOrder="100"
        />
    </type>
</config>
```

**Plugin\CustomerApproval/Helper/Data.php**
```
<?php
namespace Vendor\Module\Plugin\CustomerApproval\Helper;

use Magento\Customer\Model\Customer;
use Magento\Customer\Model\CustomerRegistry;
use Magento\Framework\Exception\NoSuchEntityException;

/**
 * Class Data
 * @package Vendor\Module\Plugin\CustomerApproval\Helper
 */
class Data
{

  /**
   * @var CustomerRegistry
   */
  protected $customerRegistry;

  /**
   * Data constructor.
   *
   * @param CustomerRegistry $customerRegistry
   */
  public function __construct(
    CustomerRegistry $customerRegistry
  ) {
    $this->customerRegistry   = $customerRegistry;
  }

  /**
   * Catch exceptions when trying to delete from carts
   *
   * @return void
   */
  public function aroundApprovalAction(
    \Mageplaza\CustomerApproval\Helper\Data $subject,
    callable $proceed,
    $customerOrId,
    string $typeApproval
  ) {

    if (is_int($customerOrId) || is_string($customerOrId)) {
      $customer = $this->customerRegistry->retrieve($customerOrId);
    } else {
      $customer = $customerOrId;
    }

    if (!$customer instanceof Customer) {
      throw new NoSuchEntityException(__('Unable to find customer.'));
    }

    $customerData = $customer->getDataModel();
    $attribute    = $customerData->getCustomAttribute('is_approved');
    if (!$attribute || $attribute->getValue() != $typeApproval) {
      $customerData->setId($customer->getId());
      $customerData->setCustomAttribute('is_approved', $typeApproval);
      $customer->updateData($customerData);
      $customer->save();
    }
  }
}
```
