### ISSUE TITLE
Unable to run the command to Approve or Not Approve customer accounts - Multi Store

### ISSUE THREAD

**Issue by fj-sfd** [mageplaza/magento-2-customer-approval#4]
![customer approve](https://user-images.githubusercontent.com/58604743/72286810-e60b4c00-3613-11ea-8bfd-77c94372c64a.PNG)

Unable to run command: php bin/magento customer:approve "email customer"
it throws error:
```
php -dmemory_limit=1G bin/magento customer:approve "fb@testdomain.com"

In CustomerRegistry.php line 121:
No such entity with email = fb@testdomain.com, websiteId = 9

customer:approve <customer-email>
```
=> My default website id is 9, seems code is checking for default store only.
=> while test email exists on another active store.

> is there a way to add store/website ids in commands?

**Comment by Arthas7895** [comment]
Can you add the code || https://prnt.sc/qntl5v
in the file
Where did you install this module\Console\Command\Approve.php
Then you run this command again and send me a result on the var/log/test.log

**Comment by vimirlab** [comment]
Same issue from backend as well. http://prntscr.com/qvjzyh

**Comment by bharatvimirlab** [comment]
Account not approved from backend as well.

Showing error message as attached.

http://prntscr.com/qvk3e1

**Comment by fj-sfd** [comment]
> Can you add the code || https://prnt.sc/qntl5v
> in the file
> Where did you install this module\Console\Command\Approve.php
> Then you run this command again and send me a result on the var/log/test.log

Hi @Arthas7895 
Sorry for late reply.
below is what i got in my test.log file:
2020-02-21T21:34:15+00:00 INFO (6): 9

=> Here, My default website id is 9.
=> while test email exists on all of my stores.

**Comment by Arthas7895** [comment]
It's very strange with your error message that there's no such customer email. Please go to the customer table and check if the email exists or not | https://prnt.sc/ri84xi

**Comment by Arthas7895** [comment]
It's been 7 days since there's no response from you, so I'll close this issue here
