### ISSUE TITLE
Admins Email sending without translation after status changing 

### ISSUE THREAD

**Issue by zkriahac** [mageplaza/magento-2-customer-approval#42]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.create account at f.e french store, the email will be sent to the customer with his lang
2. after customer approval from backend will be send without translation 

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by KhietNguyen83** [comment]
Hi @zkriahac ,
I'm Justin from Mageplaza.
I am checking your issue and will update it in new version.
