### ISSUE TITLE
Bypass: same email with different approval status (multi store)

### ISSUE THREAD

**Issue by bamdadsabbagh** [mageplaza/magento-2-customer-approval#5]
Found a scenario that can **bypass** approval.

## Required context

- 2 stores
	- First with auto approval **OFF**
	- Second with auto approval **ON**

## Steps to reproduce

1. First store
	- Create a customer account with **set email address**.
	- Login
	- Notice non approbation error
2. Second store
	- Create a customer account with **same email address**
	- Login
	- Successful login
3. Go back to first store
	- Login with account created in step 1
	- Successful login

## Expected

- Login at step 3 should be impossible.

## Follow up

- Admin section shows the right data
	- One account **pending**
	- One account **approved**
- I didn't take time to look at the code yet, but it seems user approval status is fetched regardless of the store.

![Screenshot 2020-01-19 at 07 29 51](https://user-images.githubusercontent.com/17913954/72676117-fb59fd80-3a8d-11ea-8345-e631e66b193d.jpg)

**Comment by Arthas7895** [comment]
I will check your scenario on my site and inform you of a result.
Thank you for your information.

**Comment by ralenaNA** [comment]
@themoonwatcher Not a bad idea but in my case all it did was reverse the issue. I was able to bypass on one site but not the other with your fix. Does anybody have an update on this problem for multi-store installations?

**Comment by KhietNguyen83** [comment]
Hi @bamdadsabbagh @ralenaNA ,
I'm Justin from Mageplaza.
We have resolved this issue and updated it in the new version.
Please update the extension and check again.

**Comment by bamdadsabbagh** [comment]
Hi @KhietNguyen83,
Thanks for the fix!
I will not be able to test it though.
Feel free to close this issue if needed.

**Comment by KhietNguyen83** [comment]
Thanks for your respond.
If there are no more problems, I will close it.
Thanks for using the mageplaza extension.
