### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null (approval.js)

### ISSUE THREAD

**Issue by bharatvimirlab** [mageplaza/magento-2-customer-approval#9]
Showing error while filtering customers

http://prntscr.com/qvl3u7

**Comment by Arthas7895** [comment]
You can add the code here | https://prnt.sc/qwmqup
Please make sure you have edited the pub as well so that the js file can be retrieved when reloading the page

**Comment by Arthas7895** [comment]
It's been over 7 days without a response from you. I will close this issue here
Thank you!
